// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrLNSqKrW657NU7eJyAhxZKVs2xGQHqec',
    appId: '1:803289000101:web:5efbd3dbce21d18319054c',
    messagingSenderId: '803289000101',
    projectId: 'waterproject-8c1a3',
    authDomain: 'waterproject-8c1a3.firebaseapp.com',
    storageBucket: 'waterproject-8c1a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8i5uEskZAFEzcHwQB-l1jsh2vWJWPVso',
    appId: '1:803289000101:android:cd304cd794d0ab7819054c',
    messagingSenderId: '803289000101',
    projectId: 'waterproject-8c1a3',
    storageBucket: 'waterproject-8c1a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu8h6JzkC4f7k-v7KDzJKEaLIumtP42zs',
    appId: '1:803289000101:ios:9361136c095c96c219054c',
    messagingSenderId: '803289000101',
    projectId: 'waterproject-8c1a3',
    storageBucket: 'waterproject-8c1a3.appspot.com',
    iosBundleId: 'com.example.waterResources',
  );
}
